#!/bin/bash
# a Kitten "decompiler", which prints the relevant part of the generated C source.

# 1. Compile the source in $1 to C
# 2. Output the preprocessed code using gcc -E
# 3. Keep only the main function
# 4. Format the code by adding newlines after semicolons and open curlies

./build/kitten $1 \
 | gcc -x c -E -  -L./build -I. \
 | tail -1 \
 | perl -pe 's/([;{])/\1\n/g'
