<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ktn</string>
	</array>
	<key>name</key>
	<string>Kitten</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockcomment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.kitten</string>
		</dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.kitten</string>
		</dict>
		<key>builtin</key>
		<dict>
			<key>match</key>
			<string>\b__[a-z_]+\b</string>
			<key>name</key>
			<string>support.function.builtin.kitten</string>
		</dict>
		<key>doublequotestring</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kitten</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kitten</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.kitten</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.kitten</string>
				</dict>
			</array>
		</dict>
		<key>functiondef</key>
		<dict>
			<key>begin</key>
			<string>^\s*(def)\s*([a-z][0-9A-Za-z_]*|[!#$%&amp;*+./;&lt;=&gt;?@^\|~-]+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.kitten</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kitten</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.functiondef.kitten</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#typesignature</string>
				</dict>
			</array>
		</dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functiondef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(choice|def|else|if|import|option)\b</string>
			<key>name</key>
			<string>keyword.control.kitten</string>
		</dict>
		<key>linecomment</key>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.kitten</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>\b[+-]?[0-9]+(?:\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.kitten</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>[!#$%&amp;*+./;&lt;=&gt;?@^\|~-]+</string>
			<key>name</key>
			<string>keyword.operator.kitten</string>
		</dict>
		<key>singlequotestring</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kitten</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kitten</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.kitten</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.kitten</string>
				</dict>
			</array>
		</dict>
		<key>typename</key>
		<dict>
			<key>match</key>
			<string>\b[A-Z][0-9A-Za-z_]*\b</string>
			<key>name</key>
			<string>storage.type.kitten</string>
		</dict>
		<key>typesignature</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typename</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.kitten</string>
	<key>uuid</key>
	<string>23d5cf35-7a0f-4f60-bfb3-84d0bf5fdab4</string>
</dict>
</plist>
